import Head from 'next/head';
import { Inter } from 'next/font/google';
import graphql from '@/lib/graphql';
import getAllProducts from '@/lib/graphql/queries/getAllProducts';
import { Grid } from '@chakra-ui/layout';
import ProductCard from '@/components/ProductCard';

const inter = Inter({ subsets: ['latin'] });

export const getStaticProps = async () => {
	const { products } = await graphql.request(getAllProducts);
	return {
		revalidate: 60,
		props: {
			products,
		},
	};
};

export default function Home(props) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Grid gridTemplateColumns='repeat(4, 1fr)' gap='5'>
				{props.products.map((product) => (
					<ProductCard key={product.id} {...product} />
				))}
			</Grid>
		</>
	);
}
